/**
 * Centralized Constants for Hori-s.FM
 * All timing, audio, color, and URL constants in one place
 */

// ============================================================================
// DJ STYLE CONFIGURATION
// ============================================================================

export const DJStyle = {
  STANDARD: "Standard (Radio Host)",
  CHILL: "Late Night Radio (Chill)",
  TECHNICAL: "Music Nerd (Facts & Stats)",
  MINIMAL: "Minimal (Just Song Names)",
  ASMR: "ASMR (Whispering)",
  CUSTOM: "Custom (User Defined)",
  DRUNK: "Drunk (Chaotic)",
} as const;

export type DJStyle = (typeof DJStyle)[keyof typeof DJStyle];

// ============================================================================
// TIMING CONSTANTS (in milliseconds)
// ============================================================================

export const TIMING = {
  // Polling & Check Intervals
  /**
   * SONG_CHECK_INTERVAL: How often the main loop checks song state and timing
   */
  SONG_CHECK_INTERVAL: 1000,

  /**
   * RETRY_DELAY: Delay between API retry attempts
   */
  RETRY_DELAY: 1000,

  /**
   * SILENCE_CHECK_INTERVAL: Interval for silence detection (if re-enabled)
   */
  SILENCE_CHECK_INTERVAL: 1000,

  // Audio Ducking & Crossfade
  /**
   * DUCK_DURATION: Time to gradually reduce music volume when DJ speaks
   */
  DUCK_DURATION: 2000,

  /**
   * UNDUCK_DURATION: Time to gradually restore music volume after DJ finishes
   */
  UNDUCK_DURATION: 3000,

  // Cooldowns & Delays
  /**
   * COOLDOWN_PERIOD: Cooldown period after a DJ intro finishes before allowing another
   */
  COOLDOWN_PERIOD: 5000,

  /**
   * THEME_COOLDOWN: Cooldown for special themes like news and weather (1 hour)
   */
  THEME_COOLDOWN: 60 * 60 * 1000,

  /**
   * MIN_TIME_BETWEEN_INTROS: Minimum time that must elapse between DJ intros
   */
  MIN_TIME_BETWEEN_INTROS: 20000,

  // Trigger Points
  /**
   * DJ_TRIGGER_TIME: Number of seconds before song end to trigger DJ intro generation
   * This allows enough time for API call + audio generation before transition
   */
  DJ_TRIGGER_TIME: 12000,

  /**
   * SILENCE_WARNING_THRESHOLD: Seconds of user silence before DJ should wrap up call (if re-enabled)
   */
  SILENCE_WARNING_THRESHOLD: 60000,

  // Audio Context & Buffer
  /**
   * CALL_CLEANUP_DELAY: Extra delay after audio queue finishes before cleanup
   */
  CALL_CLEANUP_DELAY: 1000,
} as const;

// ============================================================================
// AUDIO CONFIGURATION
// ============================================================================

export const AUDIO = {
  // Sample Rates (in Hz)
  /**
   * SAMPLE_RATE_OUTPUT: Output sample rate for TTS audio generated by Gemini
   */
  SAMPLE_RATE_OUTPUT: 24000,

  /**
   * SAMPLE_RATE_INPUT: Input sample rate for live call audio processing
   */
  SAMPLE_RATE_INPUT: 16000,

  // Buffer Sizes
  /**
   * BUFFER_SIZE: Audio processing buffer size for ScriptProcessor
   */
  BUFFER_SIZE: 4096,

  // Volume Levels (0.0 - 1.0)
  /**
   * DUCK_GAIN: Volume level when music is ducked for DJ voice-over (20%)
   */
  DUCK_GAIN: 0.2,

  /**
   * FULL_GAIN: Volume at full level (100%)
   */
  FULL_GAIN: 1.0,

  // Audio Normalization
  /**
   * PCM_MAX_VALUE: Maximum value for 16-bit PCM audio samples
   */
  PCM_MAX_VALUE: 32768,

  // Live Audio Settings
  /**
   * LIVE_AUDIO_CHANNELS: Number of audio channels for live calls (mono)
   */
  LIVE_AUDIO_CHANNELS: 1,
} as const;

// ============================================================================
// COLOR PALETTES
// ============================================================================

export const COLORS = {
  /**
   * NEON: Vibrant neon color palette
   */
  NEON: {
    PRIMARY: '#ff2a6d',
    SECONDARY: '#05d9e8',
    TERTIARY: '#00ff9f',
  },

  /**
   * PASTEL: Soft pastel color palette
   */
  PASTEL: {
    PRIMARY: '#ffb7b2',
    SECONDARY: '#a2e1db',
    TERTIARY: '#e2f0cb',
  },

  /**
   * MIDNIGHT: Dark midnight color palette
   */
  MIDNIGHT: {
    PRIMARY: '#7c4dff',
    SECONDARY: '#448aff',
    TERTIARY: '#69f0ae',
  },

  /**
   * GOLD: Luxurious gold color palette
   */
  GOLD: {
    PRIMARY: '#ffd700',
    SECONDARY: '#c0c0c0',
    TERTIARY: '#ffffff',
  },

  /**
   * DEFAULT_THEME_BASE: Base color used in CSS themes
   */
  DEFAULT_THEME_BASE: '#991a31',
} as const;

// ============================================================================
// API ENDPOINTS & EXTERNAL URLS
// ============================================================================

export const URLS = {
  /**
   * GOOGLE_AI_STUDIO: URL for Google AI Studio API key management
   */
  GOOGLE_AI_STUDIO: 'https://aistudio.google.com/app/apikey',

  /**
   * GOOGLE_FONTS_CSS: Google Fonts CSS URL for Inter font family
   */
  GOOGLE_FONTS_CSS: 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap',

  /**
   * REMOTE_WEB_APP: URL for the Remote Client Web App
   */
  REMOTE_WEB_APP: 'https://horizon.matejpesl.cz',
} as const;

// ============================================================================
// TYPE EXPORTS (for type safety and autocomplete)
// ============================================================================

export type TimingKey = keyof typeof TIMING;
export type AudioKey = keyof typeof AUDIO;
export type ColorPalette = keyof typeof COLORS;
